global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s

  # Flink JobManager metrics
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']
    scrape_interval: 30s

  # Flink TaskManager metrics
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9249']
    scrape_interval: 30s

  # Redis metrics (via redis_exporter if added later)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: /minio/v2/metrics/cluster

  # Application services
  - job_name: 'bluesky-producer'
    static_configs:
      - targets: ['bluesky-producer:8000']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'trend-processor'
    static_configs:
      - targets: ['trend-processor:8001']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker container metrics (if cAdvisor is added later)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s